library(dplyr)
library(lubridate)
path<-"household_power_consumption.txt"
df <- read.table(path,header=T,sep=";",na.strings="?")
df<-rename(df,date=Date,time=Time)
df$date=dmy(df$date)
df<-subset(df,date==dmy("01022007") | date==dmy("02022007"))
df$datetime<-paste(as.character(df$date),df$time,sep=" ")
df$datetime<-ymd_hms(df$datetime)
png(file="plot3.png",width=480, height=480)
par(mfrow=c(1,1))
with(df,plot(datetime,Sub_metering_1,col="grey",type='l',lwd=1,ylab="Energy sub metering",xlab=""))
lines(df$datetime,df1$Sub_metering_2,col="red",lwd=1)
lines(df$datetime,df1$Sub_metering_3,col="blue",lwd=1)
legend("topright",legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3")
       ,lty=1,lwd=2,col=c("grey","red","blue"))
dev.off()
